# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 07:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=50, verbose_name='Name')),
                ('type', models.CharField(choices=[('H', 'HOUSE'), ('L', 'LAND'), ('A', 'APARTMENT')], default='H', max_length=1)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('plan', models.CharField(choices=[('S', 'SILVER'), ('G', 'GOLD'), ('D', 'DIAMOND')], default='S', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
