# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
