# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promanage', '0002_auto_20170603_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='type',
            new_name='property_type',
        ),
        migrations.AddField(
            model_name='property',
            name='service_type',
            field=models.CharField(choices=[('RE', 'RENTAL'), ('SA', 'SALE'), ('MA', 'MAINTENANCE'), ('CO', 'CONSTRUCTION')], default='MA', max_length=2),
        ),
    ]
