# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promanage', '0003_auto_20170605_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
