# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promanage', '0004_auto_20170605_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
