# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promanage', '0005_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
