# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import promanage.models


class Migration(migrations.Migration):

    dependencies = [
        ('promanage', '0006_property_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=promanage.models.upload_location),
        ),
    ]
