# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promanage', '0007_auto_20170605_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='plan',
            field=models.CharField(choices=[('SILVER', 'SILVER'), ('GOLD', 'GOLD'), ('DIAMOND', 'DIAMOND')], default='SILVER', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'HOUSE'), ('LAND', 'LAND'), ('APARTMENT', 'APARTMENT')], default='HOUSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='service_type',
            field=models.CharField(choices=[('RENTAL', 'RENTAL'), ('SALE', 'SALE'), ('MAINTENANCE', 'MAINTENANCE'), ('CONSTRUCTION', 'CONSTRUCTION')], default='MAINTENANCE', max_length=20),
        ),
    ]
