# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promanage', '0011_maintenancerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ('-date',)},
        ),
    ]
