# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promanage', '0012_auto_20170614_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={},
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='issue_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='describe_issue',
            field=models.TextField(null=True, verbose_name='Describe Issue'),
        ),
    ]
