# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promanage', '0014_rentalproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalproperty',
            options={'verbose_name': 'RentalProperty', 'verbose_name_plural': 'RentalProperties'},
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='rent_amount',
            field=models.IntegerField(default=0),
        ),
    ]
