# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import promanage.models


class Migration(migrations.Migration):

    dependencies = [
        ('promanage', '0015_auto_20170624_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproperty',
            name='thumbnail_1',
            field=models.ImageField(null=True, upload_to=promanage.models.upload_location),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='thumbnail_2',
            field=models.ImageField(null=True, upload_to=promanage.models.upload_location),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='thumbnail_3',
            field=models.ImageField(null=True, upload_to=promanage.models.upload_location),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='thumbnail_4',
            field=models.ImageField(null=True, upload_to=promanage.models.upload_location),
        ),
    ]
