# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promanage', '0016_auto_20170628_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproperty',
            name='is_not_available',
            field=models.BooleanField(default=False),
        ),
    ]
