# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promanage', '0017_rentalproperty_is_not_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalproperty',
            name='is_not_available',
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
