# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promanage', '0018_auto_20170628_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField(default=0)),
                ('rent_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promanage.RentalProperty')),
            ],
        ),
    ]
