# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170525_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
