# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 16:06
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170606_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_location),
        ),
    ]
